# Generated by Django 4.0.5 on 2022-06-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVTLucinaApp', '0002_familiaextendida_rename_familiar_familiaconviviente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliarConviviente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('parentezco', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliarExtendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('parentezco', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='FamiliaConviviente',
        ),
        migrations.DeleteModel(
            name='FamiliaExtendida',
        ),
    ]
